version: '2'
services:
  staticman:
    build: .
    env_file: .env
    ports:
      - '8080:3000'
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      GITHUB_TOKEN: #insert your GitHub token here
      GITHUB_APP_ID: 1451374
      RSA_PRIVATE_KEY:
      GITHUB_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----YMIIEpAIBAAKCAQEAr6XYqoQZF+QyHZR6gErEdZJQsNhTDuXonFffBcLeSGXAJWQQ
MPz8xjfklVX0m+EMzX0TYpOh9jNX/7hwAhqhPAEgon19qAP6KwtDTYbhGb0u1laJ
YMLejWHk5OI27jAZsZftm5x+JZ94vLhd7queijstTcG0D3CEYXD26AOdTfMq0u/k
mRgAuahCGTkcaFPbrL+XPY4q+6OwRpfkoI3vNxoSAde9bRGwRf4+b9WqyVLhqxZy
oiTOukb0WdUSK6r3l0e0aaq6AJuzPtBujPm5fCWSvxK2YhC/50yS4hkkY6vcGdSb
m9lNVVleMDI6qk27b7aOl3Jkcj2R5RaTKqIi/wIDAQABAoIBAEyZ0jzC8UKXFTgL
OcVbVgRENAZ7wPU9VM1iEPQtQM1n+n0T/2+t1PsJAxoRa2TTp8ax5lNWOQrq51Sx
db+lJ23IvBfBDJzKZz6AYfCcguy7sYJuKOlW8sHL0Iv1D6metoXZ0RjNDcKQopID
AYwFslVsa1x+vm0BT+pC3pregKquSZogO8pH4Zi0+bRngn6Q1kuDwetBMz3QJOCm
L081nw8C9f674lJw+2ixI5fXC7Sd4uoVfuwkmK2mdarWlo+42d1yMOUfQdt0tk2p
hEYV5Q2po648ws6d6qH0dyebob7NjhNMy8YeeI1YQd3T+vCyO0I3fRKxNML8Kxv1
2lirAAkCgYEA2W6SaTOqdW2l7BS1WO8t/li4ZlaJMeZNEG8f8sByicpZhjuBRjz2
YfJWuv9sP3dBtCffJ3NvBnQJsfJc7/bdyqhpQl0COhKf11hOymepnGc1WA5//qXm
DRueo3gpw+NfVJPkgP3Q65GW91/lbja+hg8CW2oxvkyNl9DXZfZYGXUCgYEAzs3j
mI464B+WE/lqQUPAlH7nn2ehxQ+chMQ6dJTVQGQSl5CdYK0SblCs+82vK+Pfb0+a
IlUz3yFjkxhZjQQEmJ7UJFOmZ2q5DQa1XAcOADDC92oxqxECjQi4cyKBQaY89EoS
CpgQsB9GVhlhq6ddespc6U6IxEbfrAtoFJg/CCMCgYEApQaMLzacgKXpEeahwU8/
fFVAF8REOtBN21RMTkWMaVJgYkYVlwa8BZkWBLXKJd1Qy/ibIWk2chJuLVYC/cpD
igYKZekLwKHUGXCX1H2bOO8IiL3wnYiys24sGGwiXt/awenBu7lo8PI+P6DUFLOO
JVeM9W8DNCkMKpbCdUvkj+UCgYB3SeXtuqUVYMLl9KmoydcNEQK0PUff7rhfEP2S
/8LeqJrc2GsfN9X40gpmGOfhTkk04NrM0Q7ht1XDpHkLUXUBQCSoa6QB5Vqmu+bj
FaKq03Wy14uc3Gv3RD95Ej8yyhxA4XT0rXB61x9wTKW9KQZP7OiZH1beuO8OQ2oe
7w70twKBgQCPA9n++JXe1ujrs1CBHB077xkecGYB9ToeTgJle7/BLtMkihMluqXq
wkYxmqoNs1THl7txjjSHVHUO9ZWadaHeu9Uq6H7uKQvBrptz2FtVLvP3WankSvzW
4Qy/NrBRPuocNZWvsleqHFjDOnKnO14L3a40HBbBwLTieeauZGr9+w==UR_KEY-----END RSA PRIVATE KEY-----"
#        RSA private key to encrypt sensitive configuration parameters with.
#        the correct format starts with "-----BEGIN RSA PRIVATE KEY-----"